config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  resources :students
  devise_for :users
  resources :users
  root 'home#index'
  get 'home/index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  #get 'users/studentpage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
 #belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    #has_many :students
    
end

app/models/user.rb
class User < ApplicationRecord
 
  enum role: [:admin , :teacher, :student]

  after_initialize :set_default_role, :if => :new_record?

  PASSWORD_FORMAT = /\A
  (?=.{8,})          # 8 or more characters
  (?=.*[[:^alnum:]]) # symbol
  /x


  
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :phone, presence: true,uniqueness: true,length: { maximum: 10 }
  validates :password,format: PASSWORD_FORMAT
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 

  def set_default_role
    self.role ||= :student
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  after_create :welcome_send
  def welcome_send
    WelcomeJob.perform_later(User.last)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    
    
    before_action :configure_permitted_parameters, if: :devise_controller?

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private
  
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      
      redirect_to root_path
    end
   
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /students or /students.json
  def index
    @students = Student.all
    authorize Student
    
  end

  # GET /students/1 or /students/1.json
  def show
  
  end

  # GET /students/new
  def new
    @student = Student.new
   authorize @student
  end

  # GET /students/1/edit
  def edit

  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)
    authorize @student
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    authorize @student
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    authorize @student
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
    
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :department, :sec, :email, :phone )
    end

    
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
    authorize Teacher
  end

  # GET /teachers/1 or /teachers/1.json
  def show
    
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
   authorize @teacher
  end


  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    authorize @teacher
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    authorize @teacher
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    
    @teacher.destroy
   
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:name, :dept, :email, :phone)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def index
        @users = User.all
        authorize User
    end
   

    def show
        @user = User.find(params[:id])
        authorize @user
    end
    def edit

    end

    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to users_path, :notice => "user deleted"
    end
    def update
        @user = User.find(params[:id])
        authorize @user
        if @user.update(post_params)
          redirect_to @user
        else
          render :edit
        end
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/home/index.html.erb
<h1> Home Page </h1>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %> </strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_error.html.erb
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong><%= alert %> </strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>College</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/header' %>
  <div class="container">
  <% if notice %>
    <%= render 'layouts/alert' %>
  <% elsif alert%>
  <%= render 'layouts/error' %>
  <% end %>
  
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm sticky-top bg-dark navbar-dark mb-3 d-flex justify-content-between">
<!-- Brand/logo -->
<a class="navbar-brand" href="#">COLLEGE</a>

<!-- Links -->
<ul class="navbar-nav">

<% if user_signed_in? %>

    <% if current_user.role == 'admin' %>
        <li class="nav-item ">
            <%= link_to 'Home', home_index_path , class:'nav-link' %>
        </li>
            <%= link_to 'admin Page', users_path , class:'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'log out',  destroy_user_session_path,method: :delete , class:'nav-link' %>
        </li>
       
    <% elsif current_user.role == 'teacher' %>
        <li class="nav-item ">
            <%= link_to 'Home', home_index_path , class:'nav-link' %>
        </li>
            <%= link_to 'teacher page', students_path , class:'nav-link' %>
        </li>
    
        <li class="nav-item">
            <%= link_to 'log out',  destroy_user_session_path,method: :delete , class:'nav-link' %>
        </li>
    <% elsif current_user.role == 'student' %>
        <li class="nav-item ">
            <%= link_to 'Home', home_index_path , class:'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'log out',  destroy_user_session_path,method: :delete , class:'nav-link' %>
        </li>
    <% end %>
<% else %>

    <li class="nav-item">
        <%= link_to 'log in',  new_user_session_path , class:'nav-link' %>
    </li>
    <li class="nav-item">
        <%= link_to 'sign up',  new_user_registration_path , class:'nav-link' %>
    </li>


<% end %>
  

</ul>
</nav>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name,class:'form-control w-50' %>
  </div>

  <div class="field form-group">
    <%= form.label :department %>
    <%= form.text_field :department ,class:'form-control w-50'%>
  </div>

  <div class="field form-group">
    <%= form.label :sec %>
    <%= form.text_field :sec,class:'form-control w-50' %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email,class:'form-control w-50'  %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone,class:'form-control w-50' %>
  </div>
  
 
<br/>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Students</h1>

<table class="table table-bordered table-hover table-striped ">
  <thead class='table-dark'>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Sec</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.department %></td>
        <td><%= student.sec %></td>
        <td><%= student.email %></td>
        <td><%= student.phone %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
<br/>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @student.department %>
</p>

<p>
  <strong>Sec:</strong>
  <%= @student.sec %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name,class:'form-control w-50' %>
  </div>

  <div class="field form-group">
    <%= form.label :department %>
    <%= form.text_field :department ,class:'form-control w-50'%>
  </div>


  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email,class:'form-control w-50'  %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone,class:'form-control w-50' %>
  </div>
  
 
<br/>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
  <% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Teachers</h1>

<table class="table table-bordered table-striped tabe-hover ">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Dept</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.dept %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.phone %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>
<br/>
<%= link_to 'go to admin page', users_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @teacher.dept %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @teacher.phone %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/users/index.html.erb
<%= link_to 'teacher' , teachers_path %>
<%= link_to 'student' , students_path %>

app/views/users/show.html.erb
<%= link_to 'studentlist' , students_path %>